modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "potattributes"
version = "${version}"
displayName = "Potattributes"
authors = "TeamPotato"
description = '''
A Minecraft mod.
'''